language: node_js
cache: yarn

script:
  - yarn lint
  - yarn test
  - yarn build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  local_dir: dist
  on:
    branch: master
